let payload = {
  viewed: false,
  body: "PP: Robert Carlisle, $75, $225, 850 480 4677, Zelle, 850 480 4677, 961429-K-A2",
  type: "chat",
  t: 1694192641,
  notifyName: "Joseph Tannoury",
  from: "120363152990279996@g.us",
  to: "13055035308@c.us",
  author: "96170471877",
  self: "in",
  ack: 1,
  invis: false,
  isNewMsg: true,
  star: false,
  kicNotified: false,
  recvFresh: true,
  isFromTemplate: false,
  pollInvalidated: false,
  isSentCagPollCreation: false,
  latestEditMsgKey: null,
  latestEditSenderTimestampMs: null,
  mentionedJidList: [],
  groupMentions: [],
  isVcardOverMmsDocument: false,
  isForwarded: false,
  hasReaction: false,
  productHeaderImageRejected: false,
  lastPlaybackProgress: 0,
  isDynamicReplyButtonsMsg: false,
  isMdHistoryMsg: false,
  stickerSentTs: 0,
  isAvatar: false,
  lastUpdateFromServerTs: 0,
  bizBotType: null,
  requiresDirectConnection: null,
  invokedBotWid: null,
  links: [],
};

let author = payload["author"].replace("@c.us","");
let message = payload['body']
